name: delete branch on close pr
on: 
  pull_request: 
    types: 
      - closed
    branches: [dev]
jobs: 
  delete_merging_branch: 
    permissions: write-all
    if: github.event.pull_request.merged == true
    runs-on: [ubuntu-latest]
    steps: 
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}